semi: false
singleQuote: false
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: false

overrides:
  - files: "*.js"
    options:
      parser: flow
  - files: "*.{ts,tsx}"
    options:
      parser: typescript