version: "3.8"
services:
  main:
    build:
      context: .
    image: node:12
    command: bash -c 'npm start'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "${PORT}:3000"
    env_file: .env
volumes:
  node_modules:
