version: "3.8"
services:
  main:
    environment:
      - NODE_ENV=development
    command: bash -c 'npm run dev'
  mongo:
    container_name: mongo
    image: mongo
    env_file: .env
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
volumes:
  mongo_data:
  mongo_config:
